version: '3'
services:
  monitor:
    image: "nanotools/nanonodemonitor"
    restart: "unless-stopped"
    ports:
     - "80:80"
    volumes:
     - "~:/opt"
  nanonode:
    image: "nanocurrency/nano"
    restart: "unless-stopped"
    ports:
     - "7075:7075/udp"
     - "7075:7075"
     - "::1:7076:7076"
    volumes:
     - "~:/root"
  watchtower:
    image: "v2tec/watchtower"
    restart: "unless-stopped"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: "enn_monitor_1 enn_nanonode_1"
